In [11]:
## NumPy, Pandas, Matplotlib, Seaborn,Scikit - Learn(Sklearn)

In [10]:
import pandas as pd

In [ ]:
## create a series
ser = pd.Series([3,4,5,6,7])

In [ ]:
ser

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [ ]:
ser2 = pd.Series(['Apple','Mango','Grapes','Orange'])
ser2

0     Apple
1     Mango
2    Grapes
3    Orange
dtype: object

In [ ]:
ser2[1:3]

1     Mango
2    Grapes
dtype: object

In [ ]:
ser3 = pd.Series([5,6,7,8,9,12,1,3,19])
ser3

0     5
1     6
2     7
3     8
4     9
5    12
6     1
7     3
8    19
dtype: int64

In [ ]:
ser3[2:7]

2     7
3     8
4     9
5    12
6     1
dtype: int64

In [ ]:
ser4 = pd.Series([5,6,7,8,9,1,3,5],index = ['r1','r2','r3','r4','r5','r6','r7','r8'])

In [ ]:
ser4

r1    5
r2    6
r3    7
r4    8
r5    9
r6    1
r7    3
r8    5
dtype: int64

In [ ]:
ser4 = pd.Series([5,6,7,8,9,1,3,5],index = ['r1','r2','r3','r4','r5','r6','7','8'])

In [ ]:
ser4

r1    5
r2    6
r3    7
r4    8
r5    9
r6    1
7     3
8     5
dtype: int64

In [ ]:
ser4['r2':'7']

r2    6
r3    7
r4    8
r5    9
r6    1
7     3
dtype: int64

In [ ]:
df = pd.read_csv('/content/sample_data/README.md')

ParserError: ignored

In [13]:
df = pd.read_csv('/content/mtcars.csv')

In [ ]:
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
## 31 observations with 10 parameters

In [ ]:
df.head() ##First five observations

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
df.head(10) ##First ten observations

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [ ]:
df.tail(7) ## Last seven observations

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.9,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [ ]:
df.shape ## Check the dataset size

(32, 12)

In [ ]:
#32 OBSERVATIONS AND 12 PARAMETERS

In [ ]:
# Check all the values of mpg
df.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [ ]:
df['mpg'] ## If there is space between column names

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

DATAFRAME

In [ ]:
df1 = pd.DataFrame([[1,2,3,4,5,6] ,[2,3,4,5,6,7],[2,3,4,5,6,7]])

In [ ]:
df1

   0  1  2  3  4  5
0  1  2  3  4  5  6
1  2  3  4  5  6  7
2  2  3  4  5  6  7

In [ ]:
df1.columns=['c1','c2','c3','c4','c5','c6']
df1.index = ['r1','r2','r3']

In [ ]:
df1

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   2   3   4   5   6   7
r3   2   3   4   5   6   7

In [26]:
import numpy as np

In [27]:
d = {'name':['A','B','C','D','E'] ,'Age':[19,22,np.nan,18,19],'Gender':['M','F','M','M','F']}

In [ ]:
d

{'name': ['A', 'B', 'C', 'D', 'E'],
 'Age': [19, 22, nan, 18, 19],
 'Gender': {'F', 'M'}}

In [28]:
df3 = pd.DataFrame(d)
df3

  name   Age Gender
0    A  19.0      M
1    B  22.0      F
2    C   NaN      M
3    D  18.0      M
4    E  19.0      F

In [ ]:
df4 = pd.DataFrame(d)

ValueError: ignored

In [ ]:
 df3.Gender

0    M
1    F
2    M
3    M
4    F
Name: Gender, dtype: object

In [ ]:
 df3['Salary']= [65000,45000,56000,33300,90000]
 df3

  name   Age Gender  Salary
0    A  19.0      M   65000
1    B  22.0      F   45000
2    C   NaN      M   56000
3    D  18.0      M   33300
4    E  19.0      F   90000

In [ ]:
df3.isnull().any()

name      False
Age        True
Gender    False
Salary    False
dtype: bool

In [ ]:
df3.shape

(5, 4)

In [ ]:
df3.drop(['Salary','name'],axis = 1)

    Age Gender
0  19.0      M
1  22.0      F
2   NaN      M
3  18.0      M
4  19.0      F

In [ ]:
# if you are dropping any column axis =1 , if deleting row in row axis = 0

In [ ]:
 df3.isnull().sum() - This gives accurate number

SyntaxError: ignored

In [ ]:
dfd = df3.drop(3, axis = 0) # this is for deleting the third index(row) from df
dfd

  name   Age Gender  Salary
0    A  19.0      M   65000
1    B  22.0      F   45000
2    C   NaN      M   56000
4    E  19.0      F   90000

In [ ]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
df.info() # This is for giving datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [7]:
 df3.info()

NameError: ignored

In [ ]:
df3.describe() # Statistical analysis of dataset, gives descriptives of data

             Age        Salary
count   4.000000      5.000000
mean   19.500000  57860.000000
std     1.732051  21540.612805
min    18.000000  33300.000000
25%    18.750000  45000.000000
50%    19.000000  56000.000000
75%    19.750000  65000.000000
max    22.000000  90000.000000

In [ ]:
# mean or median - numerical features
# mode - Categorical features

In [ ]:
df3.Age.median()

19.0

In [ ]:
df3.Age.mean()

19.5

In [ ]:
df3.Age = df3.Age.fillna(df3.Age.median())

In [23]:
df3

NameError: ignored

In [ ]:
df3.Gender.mode()

0    M
Name: Gender, dtype: object

In [ ]:
# Slicing operators
# loc - location
# iloc - index location

In [ ]:
df.loc[3] ## gives all properties of third observation

model    Hornet 4 Drive
mpg                21.4
cyl                   6
disp              258.0
hp                  110
drat               3.08
wt                3.215
qsec              19.44
vs                    1
am                    0
gear                  3
carb                  1
Name: 3, dtype: object

In [ ]:
df.loc[0]

model    Mazda RX4
mpg           21.0
cyl              6
disp         160.0
hp             110
drat           3.9
wt            2.62
qsec         16.46
vs               0
am               1
gear             4
carb             4
Name: 0, dtype: object

In [ ]:
# create  a pandas dataframe - 4 fearures and 4 observations
# check the info of df
# 5 features , obvservations- 10

In [14]:
# loc - location, iloc - index location
# loc[:,:] , iloc[:,:]

df.loc[1:3,'model':'hp']

            model   mpg  cyl   disp   hp
1   Mazda RX4 Wag  21.0    6  160.0  110
2      Datsun 710  22.8    4  108.0   93
3  Hornet 4 Drive  21.4    6  258.0  110

In [15]:
df.iloc[1:4,0:5]

            model   mpg  cyl   disp   hp
1   Mazda RX4 Wag  21.0    6  160.0  110
2      Datsun 710  22.8    4  108.0   93
3  Hornet 4 Drive  21.4    6  258.0  110

In [16]:
df.mpg.dtypes

dtype('float64')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [19]:
# Encoding - converting object datatype to int or float for passing to algorithms
'''

1) One hot encodinig
2) Label encoding
3) Manual encoding

'''

'\n\n1) One hot encodinig\n2) Label encoding\n3) Manual encoding\n\n'

In [20]:
# One hot encoding

pd.get_dummies(df['model'])

,AMC Javelin,Cadillac Fleetwood,Camaro Z28,Chrysler Imperial,Datsun 710,Dodge Challenger,Duster 360,Ferrari Dino,Fiat 128,Fiat X1-9,...,Merc 280C,Merc 450SE,Merc 450SL,Merc 450SLC,Pontiac Firebird,Porsche 914-2,Toyota Corolla,Toyota Corona,Valiant,Volvo 142E
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
# converts all the rows to columns - categorical to numerical

In [22]:
df3

NameError: ignored

In [29]:
df3

  name   Age Gender
0    A  19.0      M
1    B  22.0      F
2    C   NaN      M
3    D  18.0      M
4    E  19.0      F

In [33]:
one_hot = pd.get_dummies(df3['Gender'])

In [31]:
# Splitting the categorical data into mulitple columns and then passing 0 and 1.

In [32]:
df3

  name   Age Gender
0    A  19.0      M
1    B  22.0      F
2    C   NaN      M
3    D  18.0      M
4    E  19.0      F

In [34]:
out = [df3,one_hot]

In [35]:
out # prints first dataframe and then next

[  name   Age Gender
 0    A  19.0      M
 1    B  22.0      F
 2    C   NaN      M
 3    D  18.0      M
 4    E  19.0      F,
    F  M
 0  0  1
 1  1  0
 2  0  1
 3  0  1
 4  1  0]

In [36]:
pd.concat(out) #combines the second frame but with null values

  name   Age Gender    F    M
0    A  19.0      M  NaN  NaN
1    B  22.0      F  NaN  NaN
2    C   NaN      M  NaN  NaN
3    D  18.0      M  NaN  NaN
4    E  19.0      F  NaN  NaN
0  NaN   NaN    NaN  0.0  1.0
1  NaN   NaN    NaN  1.0  0.0
2  NaN   NaN    NaN  0.0  1.0
3  NaN   NaN    NaN  0.0  1.0
4  NaN   NaN    NaN  1.0  0.0

In [38]:
df3 = df3.join(one_hot)

In [39]:
df3

  name   Age Gender  F  M
0    A  19.0      M  0  1
1    B  22.0      F  1  0
2    C   NaN      M  0  1
3    D  18.0      M  0  1
4    E  19.0      F  1  0

In [40]:
df5 = pd.get_dummies(df3,columns = ['Gender'],drop_first = True )

In [41]:
df5

  name   Age  F  M  Gender_M
0    A  19.0  0  1         1
1    B  22.0  1  0         0
2    C   NaN  0  1         1
3    D  18.0  0  1         1
4    E  19.0  1  0         0

In [42]:
df_enc = pd.get_dummies()

TypeError: ignored

In [43]:
df_enc = pd.get_dummies(df['model'])

In [44]:
df_new = df.join(df_enc)

In [45]:
df_new

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,...,Merc 280C,Merc 450SE,Merc 450SL,Merc 450SLC,Pontiac Firebird,Porsche 914-2,Toyota Corolla,Toyota Corona,Valiant,Volvo 142E
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,...,0,0,0,0,0,0,0,0,0,0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,...,0,0,0,0,0,0,0,0,0,0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,...,0,0,0,0,0,0,0,0,0,0
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,...,0,0,0,0,0,0,0,0,0,0
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,...,0,0,0,0,0,0,0,0,1,0
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,...,0,0,0,0,0,0,0,0,0,0
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,...,0,0,0,0,0,0,0,0,0,0
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,...,0,0,0,0,0,0,0,0,0,0
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,...,0,0,0,0,0,0,0,0,0,0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,...,1,0,0,0,0,0,0,0,0,0
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,...,0,1,0,0,0,0,0,0,0,0
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,...,0,0,1,0,0,0,0,0,0,0
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,...,0,0,0,1,0,0,0,0,0,0
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,...,0,0,0,0,0,0,0,0,0,0
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,...,0,0,0,0,0,0,0,0,0,0
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,...,0,0,0,0,0,0,0,0,0,0
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,...,0,0,0,0,0,0,1,0,0,0
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,...,0,0,0,0,0,0,0,1,0,0
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,...,0,0,0,0,0,0,0,0,0,0
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,...,0,0,0,0,1,0,0,0,0,0
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,...,0,0,0,0,0,0,0,0,0,0
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,...,0,0,0,0,0,1,0,0,0,0
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,...,0,0,0,0,0,0,0,0,0,0
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,...,0,0,0,0,0,0,0,0,0,0
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,...,0,0,0,0,0,0,0,0,0,0
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,...,0,0,0,0,0,0,0,0,0,0
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,...,0,0,0,0,0,0,0,0,0,1

In [47]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Label encoder accepts alphabetical order so F will come first and first will be replaced by 0 and then 1 and then so on

In [49]:
df3['Gender'] = le.fit_transform(df3['Gender'])
df3

  name   Age  Gender  F  M
0    A  19.0       1  0  1
1    B  22.0       0  1  0
2    C   NaN       1  0  1
3    D  18.0       1  0  1
4    E  19.0       0  1  0

In [51]:
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [52]:
df['model'] = le.fit_transform(df['model'])

In [53]:
df

    model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      17  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      18  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2       4  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      12  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4      13  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5      30  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6       6  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7      20  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8      19  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9      21  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10     22  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11     23  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12     24  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13     25  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14      1  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15     14  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16      3  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17      8  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18     11  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19     28  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20     29  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21      5  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22      0  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23      2  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     26  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25      9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26     27  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27     15  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28     10  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29      7  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30     16  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31     31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [54]:
le.inverse_transform([9]) # To get the value associated to the label i.e index

array(['Fiat X1-9'], dtype=object)